-- 兑换码数据库初始化脚本
-- 用于阿里云服务器MySQL数据库

-- 创建数据库
CREATE DATABASE IF NOT EXISTS redeem_codes CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE redeem_codes;

-- 创建兑换码表
CREATE TABLE IF NOT EXISTS redeem_codes (
    code VARCHAR(50) PRIMARY KEY COMMENT '兑换码',
    type VARCHAR(20) NOT NULL COMMENT '类型：supporter/gm',
    is_valid TINYINT(1) DEFAULT 1 COMMENT '是否有效',
    max_uses INT DEFAULT 1 COMMENT '最大使用次数',
    used_count INT DEFAULT 0 COMMENT '已使用次数',
    used_by_user_id VARCHAR(100) DEFAULT NULL COMMENT '使用用户ID',
    used_at DATETIME DEFAULT NULL COMMENT '使用时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX idx_type (type),
    INDEX idx_used_by_user_id (used_by_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='兑换码表';

-- 创建用户兑换码表
CREATE TABLE IF NOT EXISTS user_redeem_codes (
    user_id VARCHAR(100) PRIMARY KEY COMMENT '用户ID',
    used_codes TEXT COMMENT '已使用的兑换码列表（JSON格式）',
    gm_mode_unlocked TINYINT(1) DEFAULT 0 COMMENT '是否解锁GM模式',
    supporter_unlocked TINYINT(1) DEFAULT 0 COMMENT '是否解锁支持者功能',
    last_updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    INDEX idx_gm_mode (gm_mode_unlocked),
    INDEX idx_supporter (supporter_unlocked)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户兑换码表';

-- 插入支持者兑换码（SUPPORTER001-150）
INSERT INTO redeem_codes (code, type) VALUES
('SUPPORTER001', 'supporter'),
('SUPPORTER002', 'supporter'),
('SUPPORTER003', 'supporter'),
('SUPPORTER004', 'supporter'),
('SUPPORTER005', 'supporter'),
('SUPPORTER006', 'supporter'),
('SUPPORTER007', 'supporter'),
('SUPPORTER008', 'supporter'),
('SUPPORTER009', 'supporter'),
('SUPPORTER010', 'supporter'),
('SUPPORTER011', 'supporter'),
('SUPPORTER012', 'supporter'),
('SUPPORTER013', 'supporter'),
('SUPPORTER014', 'supporter'),
('SUPPORTER015', 'supporter'),
('SUPPORTER016', 'supporter'),
('SUPPORTER017', 'supporter'),
('SUPPORTER018', 'supporter'),
('SUPPORTER019', 'supporter'),
('SUPPORTER020', 'supporter'),
('SUPPORTER021', 'supporter'),
('SUPPORTER022', 'supporter'),
('SUPPORTER023', 'supporter'),
('SUPPORTER024', 'supporter'),
('SUPPORTER025', 'supporter'),
('SUPPORTER026', 'supporter'),
('SUPPORTER027', 'supporter'),
('SUPPORTER028', 'supporter'),
('SUPPORTER029', 'supporter'),
('SUPPORTER030', 'supporter'),
('SUPPORTER031', 'supporter'),
('SUPPORTER032', 'supporter'),
('SUPPORTER033', 'supporter'),
('SUPPORTER034', 'supporter'),
('SUPPORTER035', 'supporter'),
('SUPPORTER036', 'supporter'),
('SUPPORTER037', 'supporter'),
('SUPPORTER038', 'supporter'),
('SUPPORTER039', 'supporter'),
('SUPPORTER040', 'supporter'),
('SUPPORTER041', 'supporter'),
('SUPPORTER042', 'supporter'),
('SUPPORTER043', 'supporter'),
('SUPPORTER044', 'supporter'),
('SUPPORTER045', 'supporter'),
('SUPPORTER046', 'supporter'),
('SUPPORTER047', 'supporter'),
('SUPPORTER048', 'supporter'),
('SUPPORTER049', 'supporter'),
('SUPPORTER050', 'supporter'),
('SUPPORTER051', 'supporter'),
('SUPPORTER052', 'supporter'),
('SUPPORTER053', 'supporter'),
('SUPPORTER054', 'supporter'),
('SUPPORTER055', 'supporter'),
('SUPPORTER056', 'supporter'),
('SUPPORTER057', 'supporter'),
('SUPPORTER058', 'supporter'),
('SUPPORTER059', 'supporter'),
('SUPPORTER060', 'supporter'),
('SUPPORTER061', 'supporter'),
('SUPPORTER062', 'supporter'),
('SUPPORTER063', 'supporter'),
('SUPPORTER064', 'supporter'),
('SUPPORTER065', 'supporter'),
('SUPPORTER066', 'supporter'),
('SUPPORTER067', 'supporter'),
('SUPPORTER068', 'supporter'),
('SUPPORTER069', 'supporter'),
('SUPPORTER070', 'supporter'),
('SUPPORTER071', 'supporter'),
('SUPPORTER072', 'supporter'),
('SUPPORTER073', 'supporter'),
('SUPPORTER074', 'supporter'),
('SUPPORTER075', 'supporter'),
('SUPPORTER076', 'supporter'),
('SUPPORTER077', 'supporter'),
('SUPPORTER078', 'supporter'),
('SUPPORTER079', 'supporter'),
('SUPPORTER080', 'supporter'),
('SUPPORTER081', 'supporter'),
('SUPPORTER082', 'supporter'),
('SUPPORTER083', 'supporter'),
('SUPPORTER084', 'supporter'),
('SUPPORTER085', 'supporter'),
('SUPPORTER086', 'supporter'),
('SUPPORTER087', 'supporter'),
('SUPPORTER088', 'supporter'),
('SUPPORTER089', 'supporter'),
('SUPPORTER090', 'supporter'),
('SUPPORTER091', 'supporter'),
('SUPPORTER092', 'supporter'),
('SUPPORTER093', 'supporter'),
('SUPPORTER094', 'supporter'),
('SUPPORTER095', 'supporter'),
('SUPPORTER096', 'supporter'),
('SUPPORTER097', 'supporter'),
('SUPPORTER098', 'supporter'),
('SUPPORTER099', 'supporter'),
('SUPPORTER100', 'supporter'),
('SUPPORTER101', 'supporter'),
('SUPPORTER102', 'supporter'),
('SUPPORTER103', 'supporter'),
('SUPPORTER104', 'supporter'),
('SUPPORTER105', 'supporter'),
('SUPPORTER106', 'supporter'),
('SUPPORTER107', 'supporter'),
('SUPPORTER108', 'supporter'),
('SUPPORTER109', 'supporter'),
('SUPPORTER110', 'supporter'),
('SUPPORTER111', 'supporter'),
('SUPPORTER112', 'supporter'),
('SUPPORTER113', 'supporter'),
('SUPPORTER114', 'supporter'),
('SUPPORTER115', 'supporter'),
('SUPPORTER116', 'supporter'),
('SUPPORTER117', 'supporter'),
('SUPPORTER118', 'supporter'),
('SUPPORTER119', 'supporter'),
('SUPPORTER120', 'supporter'),
('SUPPORTER121', 'supporter'),
('SUPPORTER122', 'supporter'),
('SUPPORTER123', 'supporter'),
('SUPPORTER124', 'supporter'),
('SUPPORTER125', 'supporter'),
('SUPPORTER126', 'supporter'),
('SUPPORTER127', 'supporter'),
('SUPPORTER128', 'supporter'),
('SUPPORTER129', 'supporter'),
('SUPPORTER130', 'supporter'),
('SUPPORTER131', 'supporter'),
('SUPPORTER132', 'supporter'),
('SUPPORTER133', 'supporter'),
('SUPPORTER134', 'supporter'),
('SUPPORTER135', 'supporter'),
('SUPPORTER136', 'supporter'),
('SUPPORTER137', 'supporter'),
('SUPPORTER138', 'supporter'),
('SUPPORTER139', 'supporter'),
('SUPPORTER140', 'supporter'),
('SUPPORTER141', 'supporter'),
('SUPPORTER142', 'supporter'),
('SUPPORTER143', 'supporter'),
('SUPPORTER144', 'supporter'),
('SUPPORTER145', 'supporter'),
('SUPPORTER146', 'supporter'),
('SUPPORTER147', 'supporter'),
('SUPPORTER148', 'supporter'),
('SUPPORTER149', 'supporter'),
('SUPPORTER150', 'supporter'),
('PROGM', 'gm');

-- 创建数据库用户（用于API连接）
-- 注意：请修改密码为强密码
CREATE USER IF NOT EXISTS 'redeem_api'@'localhost' IDENTIFIED BY 'your_secure_password_here';
GRANT ALL PRIVILEGES ON redeem_codes.* TO 'redeem_api'@'localhost';
FLUSH PRIVILEGES;

-- 验证数据
SELECT COUNT(*) as total_codes FROM redeem_codes;
SELECT COUNT(*) as supporter_codes FROM redeem_codes WHERE type = 'supporter';
SELECT COUNT(*) as gm_codes FROM redeem_codes WHERE type = 'gm';

